[package]
name = "pdf2latex"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
bitcode = "0.4.0"
clap = { version = "4.3.5", features = ["derive"] }
dirs = "5.0.1"
unicode-segmentation = "1.10.1"
strsim = "0.10.0"
