[package]
name = "pdf2latex"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
clap = { version = "4.3.5", features = ["derive"] }
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
dirs = "5.0.1"
unicode-segmentation = "1.10.1"
strsim = "0.10.0"
