[package]
name = "pdf2latex"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "utils",
    "font_base_generator"
]

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
image = "0.24.6"

utils = { path = "utils"}
