[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
bitcode = "0.4.0"
clap = { version = "4.3.5", features = ["derive"] }
dirs = "5.0.1"
